### ISSUE TITLE
plugin sounds not working

### ISSUE THREAD

**Issue by sandman-pvm** [EwwItsMike/ImaDrum-Money#3]
I'm not sure what's going on however i feel that the plugin was working flawlessly for pets and drops for a long time and has broken since the stackable clues update came out?.

I've been camping venenatis and have had 2 gem drops 40m and countless onyx bolt tip drops which usually pleasure my ears with your plugin sounds however haven't heard anything . I've tried everything from changing drop value threshold,  reset settings, manually deleting plugin files and re installing, sound driver updates and graphics updates etc etc.. if there's anything you can suggest I'm all ears. cheers mate!

**Comment by EwwItsMike** [comment]
I was just notified by this by a friend of mine not even 5 minutes before you wrote this, lol.
I'm currently investigating, it has to do with switching to a different way of playing audio (new RuneLite requirement) which I did during the last update for stackable clues.

It's not a problem on your end! The plugin is posting an error in the Client log, it seems to be broken for everyone. 
(except in my test build....)

**Comment by sandman-pvm** [comment]
oooooh thanks for the super fast reply man! your plugin has literally made the game absolutely amazing! I'm just so sad i didn't get to hear what it would have yelled out with the voidwaker gem drops haha XD.

I'm super grateful for your plugin mate. funny timing too, i made a runelite and github acc just to post this, so thanks again for the speedy reply! will you update this page with an eta when you figure out whats wrong? thanks again <3

**Comment by EwwItsMike** [comment]
It appears I made a mistake in how I was sending the sound files to the RuneLite Audio player, which did not prevent sound clips from playing during testing, lol.
I've sent the update to the Plugin Hub maintainers, so as soon as they review and accept it, a client restart should fix it!
I'll put another message in here once they have :)

**Comment by sandman-pvm** [comment]
Woooohoooo! "MOOOOONNNNNNNEYYYYYYYYYYYYY!!!".

if i can ask, did you record yourself / someone or is it ai or something like that?, its literally perfect!!.

cheers from Australia, Rob.

**Comment by EwwItsMike** [comment]
It's Drum himself! asked him to supply the clips haha

**Comment by EwwItsMike** [comment]
Plugin is now updated! A client restart should get it done :)

**Comment by sandman-pvm** [comment]
thanks for the update, i tried restarting client, deleting plugin and re downloading and it appears it still isnt working on my end. ill try and diagnose on my end later in the day. 
thanks again. Rob,

**Comment by EwwItsMike** [comment]
Unfortunately it doesn't work on my end either... very annoying running the tests doesn't actually run the same thing as when a plugin is submitted. 
Reopening until actually fixed 🙃 

EDIT: I am just too damn tired. Turns out the notification I got was just the changes being approved, but never merged into the actual plugin hub.

**Comment by sandman-pvm** [comment]
try cand catch up on some sleep, best thing for us scapers. thanks again for working hard and being so attentive, I'm sure everyone that uses your plugin is super grateful for all your hard work and perfect plugin!
cheers!

**Comment by shore714** [comment]
missed my clue scroll and superior spawns :(

**Comment by EwwItsMike** [comment]
I've received some help from RuneLite admins, I HOPE it's going to be actually fixed very soon :)

**Comment by sandman-pvm** [comment]
wooooohooooo! MONEYYYY! so excited!

**Comment by WalterLaguna** [comment]
Buenas ami tampoco me funciona el money pero los otros si cuando dice collection log xq sera quien me ayuda

**Comment by EwwItsMike** [comment]
It seems the plugin works as intended again!

**Comment by sandman-pvm** [comment]
yes its working for me now at bandos! woohooo!!! thanks mate
